hw_info:
  cpu_id: ""
  cpu_name: ck802
  vendor_name: ""
  chip_name: ""
  board_name: ""
  ld_script: ../board/gcc_flash.ld
  flash_program: ""
def_config:
  CONFIG_ARCH_INTERRUPTSTACK: 1024
  CONFIG_DEBUG_MODE: 1
  CONFIG_KERNEL_NONE: 1
  CONFIG_SUPPORT_TSPEND: 1
  CONFIG_USER_PM: 1
  CONFIG_XIP: 1
  DBG_PRINT2PC: 1
name: apt32f171x
version: v0.0.0
description: 我的第一个方案工程
tag: ""
keywords: 
author:
  name: ""
license: ""
type: solution
depends:
  - apt32f171x_demo: v0.0.0
  - sdk_171x: v0.0.0
build_config:
  include:
    - include
    - ./
  internal_include: 
  cflag: -Og  -g  -Wall
  cxxflag: -Og  -g  -Wall
  asmflag: -Wa,--gdwarf2
  define: 
  libs: 
  libpath: 
source_file:
  - src/*.c
install: 
homepage: 
depends_forward:
  - apt32f171x_demo: v0.0.0
  - sdk_171x: v0.0.0