name: apt32f171x_demo_pro
version: V1.0.1
description: demo to provide reference code
tag: ""
keywords: 
author:
  name: ""
license: ""
homepage: 
type: common
depends: 
yoc_version: 
hw_info:
  cpu_id: ""
  cpu_name: ""
  vendor_name: ""
  chip_name: ""
  board_name: ""
  ld_script: ""
  flash_program: ""
build_config:
  include:
    - include
  internal_include: 
  cflag: -Og  -g3
  cxxflag: -Og  -g3
  asmflag: -Wa,--gdwarf2
  define: 
  libs: 
  libpath: 
source_file:
  - src/*.c
def_config: 
install: 
depends_forward: 