/**
  * Auto Generated by CDK.
  * Do not modify this file, and any manual changes will be erased!!!
  */


#include "csi_drv.h"

void pin_init(void)
{
}

void sys_clock_init(void)
{
	CK_CPU_DISALLNORMALIRQ;
	g_tClkConfig.eClkSrc = SRC_IMOSC;
	g_tClkConfig.wFreq   = IMOSC_5M_VALUE;
	g_tClkConfig.eSdiv   = SCLK_DIV1;
	g_tClkConfig.ePdiv   = PCLK_DIV2;
	g_tClkConfig.wSclk   = 5556000;
	g_tClkConfig.wPclk   = 5556000;

	csi_sysclk_config(g_tClkConfig);
	csi_calc_clk_freq();
	CK_CPU_ENALLNORMALIRQ;
}

void sys_lvr_init(void)
{
	csi_lvr_enable(LVR_19);
	csi_lvd_int_enable(LVD_INTR,LVD_21);
}

void sys_sramcheck_init(void)
{
	csi_sramcheck_set_times(0xffff);
	csi_sramcheck_rst();
}

void sys_flashcheck_init(void)
{
	csi_flashcheck_set_times(0xffffff);
	csi_flashcheck_rst();
}

void sys_emclockmonitor_init(void)
{
	csi_emcm_rst();
}

void sys_iwdt_init(void)
{
	csi_iwdt_init(IWDT_TO_128);
	csi_iwdt_open();
	csi_iwdt_feed();
}

void sys_tick_init(void)
{
	csi_tick_init();
}

void EXIGRP0_init(void)
{
	csi_pin_irq_enable(PA00, ENABLE);
	csi_pin_irq_mode(PA00, EXI_GRP0, GPIO_IRQ_RISING_EDGE);
	csi_pin_vic_irq_enable(EXI_GRP0, ENABLE);
}

void adc_init(void)
{
	csi_adc_seq_t tSeqCfg[] =
	{
		{ADCIN0,	ADC_CV_COUNT_1,	ADC_AVG_COF_1,	ADCSYNC_NONE},
	};
	static uint8_t 	s_byChnlNum = sizeof(tSeqCfg) / sizeof(tSeqCfg[0]); 
	csi_adc_config_t tAdcConfig;

	tAdcConfig.byClkDiv   = 0x01;
	tAdcConfig.bySampHold = 0x03;
	tAdcConfig.byConvMode = ADC_CONV_ONESHOT;
	tAdcConfig.byVrefSrc  = ADCVREF_FVR2048_VREFN;
	tAdcConfig.wInt       = ADC_INTSRC_NONE;
	tAdcConfig.ptSeqCfg   = (csi_adc_seq_t *)tSeqCfg;

	csi_adc_init(ADC0, &tAdcConfig);
	csi_adc_set_seqx(ADC0, tAdcConfig.ptSeqCfg, s_byChnlNum);
	csi_adc_start(ADC0);
}

void cmp0_init(void)
{
	csi_cmp_config_t tCmpCfg;
	tCmpCfg.byNsel     = CMP_N_SEL_CP0;
	tCmpCfg.byPsel     = CMP_P_SEL_CP0;
	tCmpCfg.byPhystpol = CMP_PHYST_POL_0mv;
	tCmpCfg.byPhystsel = CMP_PHYST_POL_DIS;
	tCmpCfg.byPolarity = CMP_POL_OUT_DIRECT;
	tCmpCfg.byCpoSel   = CMP_CPOS_OUT_DIRECT;
	tCmpCfg.wInt       = CMP_INTSRC_NONE;
	csi_cmp_init(CMP0,&tCmpCfg);

	csi_cmp_start(CMP0);
}

void uart0_init(void)
{
	csi_uart_config_t tUartConfig;
	tUartConfig.wBaudRate   = 115200;
	tUartConfig.byParity    = UART_PARITY_NONE;
	tUartConfig.hwRecvTo    = 88;
	tUartConfig.byTxMode	= UART_TX_MODE_INT;
	tUartConfig.byRxMode	= UART_RX_MODE_POLL;
	tUartConfig.wInt		= UART_INTSRC_TXDONE;
	
	csi_uart_init(UART0, &tUartConfig);
	csi_uart_start(UART0, UART_FUNC_RX_TX);
}

void usart0_init(void)
{
	csi_usart_config_t tUsartCfg;
	tUsartCfg.byClkSrc  = USART_CLKSRC_DIV1;
	tUsartCfg.byMode	= USART_MODE_ASYNC;
	tUsartCfg.byDatabit = USART_DATA_BITS_8;
	tUsartCfg.byStopbit = USART_STOP_BITS_1;
	tUsartCfg.byParity  = USART_PARITY_NONE;
	tUsartCfg.bClkOutEn	= DISABLE;
	tUsartCfg.wBaudRate = 115200;
	tUsartCfg.hwRecvTo	= 88;
	tUsartCfg.bRecvToEn	= DISABLE;
	tUsartCfg.byTxMode	= USART_TX_MODE_POLL;
	tUsartCfg.byRxMode	= USART_RX_MODE_POLL;
	tUsartCfg.wInt		= USART_INTSRC_NONE;

	csi_usart_init(USART0, &tUsartCfg);
	csi_usart_start(USART0, USART_FUNC_RX_TX);
}

void wwdt_init(void)
{
	csi_wwdt_init(80);
	csi_wwdt_debug_enable(ENABLE);
	csi_wwdt_set_window_time(40);
	csi_wwdt_open();
}

void bt0_init(void)
{
	csi_bt_timer_init(BT0, 10000);
	csi_bt_start(BT0);
}

void etcbch0_init(void)
{
	csi_etb_config_t tEtbConfig;
	tEtbConfig.bySrcIp  = ETB_SRC_NOT_USE;
	tEtbConfig.bySrcIp1 = ETB_SRC_NOT_USE;
	tEtbConfig.bySrcIp2 = ETB_SRC_NOT_USE;
	tEtbConfig.byDstIp  = ETB_LPT_SYNCIN0;
	tEtbConfig.byChType = ETB_MORE_TRG_ONE;
	tEtbConfig.byTrgMode = ETB_HARDWARE_TRG;
	csi_etb_init();
	csi_etb_ch_config(0, &tEtbConfig);
}

void ept0_init(void)
{
	csi_ept_captureconfig_t   tCapCfg;
	tCapCfg.byWorkmod         = EPT_CAPTURE;
	tCapCfg.byCountingMode    = EPT_UPCNT;
	tCapCfg.byCaptureCapmd    = EPT_CAPMD_CONT;
	tCapCfg.byCaptureStopWrap = 3;
	tCapCfg.byCaptureLdaret   = 0;
	tCapCfg.byCaptureLdbret   = 0;
	tCapCfg.byCaptureLdcret   = 0;
	tCapCfg.byCaptureLddret   = 0;
	tCapCfg.wInt 	          = EPT_INTSRC_NONE;

	csi_ept_capture_init(EPT0, &tCapCfg);
}

void gpta_init(void)
{
	csi_gpta_timer_init(GPTA0, 10000);
	csi_gpta_start(GPTA0);
}


void __attribute__ ((weak)) __ChipInitHandler(void)
{
	sys_clock_init();
	sys_lvr_init();
	sys_sramcheck_init();
	sys_flashcheck_init();
	sys_emclockmonitor_init();
	sys_iwdt_init();
	sys_tick_init();
	pin_init();
	EXIGRP0_init();
	adc_init();
	cmp0_init();
	uart0_init();
	usart0_init();
	wwdt_init();
	bt0_init();
	etcbch0_init();
	ept0_init();
	gpta_init();
}

