/**
  * Auto Generated by CDK.
  * Do not modify this file, and any manual changes will be erased!!!
  */


#include "soc.h"
#include "drv/gpio.h"
#include "drv/pin.h"


void PinConfigInit(void)
{
}

void __attribute__ ((weak)) __ChipInitHandler(void)
{
    PinConfigInit();
}
