name: apt_console
version: v1.0.1
description: mini console.
tag: 核心模块
keywords:
  - base
license: Apache license v2.0
hidden: true
type: common
yoc_version:
  - v7.2
  - v7.3
depends:
  - apt_csi: v1.2.3
build_config:
  include:
    - include
  internal_include: 
  cflag: -Os
  cxxflag: -Os
  asmflag: ""
  define: 
  libs: 
  libpath: 
source_file:
  - src/*.c
  - include/sys_console.h
install:
  - dest: include/console
    source:
      - console/*.h
author: ""
defconfig: 
link_config:
  path: 
  library: 
field: 
suitableChip: 
homepage: 
soc_config: 
depends_forward:
  - apt_csi: v1.2.3